description: ArteWil - software development and music mixing

profileMode:
  enabled: true
  imageTitle: ArteWil logo
  subtitle: Software development and music mixing
  buttons:
    - name: Music
      url: music

socialIcons:
  - name: LinkedIn
    url: https://www.linkedin.com/company/artewil
  - name: GitHub
    url: https://github.com/vilchy
  - name: Pixabay
    url: https://pixabay.com/users/rotepian-14403633
  - name: Discogs
    url: https://www.discogs.com/artist/1884887-Artur-Wilniewczyc
  - name: YouTube
    url: https://youtube.com/playlist?list=PLeMSV_3ixFZlS4cU7VSM3TujMToW2AqYo
