# SPDX-FileCopyrightText: 2023 Artur Wilniewczyc <artur.wilniewczyc@gmail.com>
#
# SPDX-License-Identifier: MIT

description: ArteWil - Softwareentwicklung und Musikmischung

profileMode:
  enabled: true
  imageTitle: ArteWil-Logo
  subtitle: Softwareentwicklung und Musikmischung
  buttons:
    - name: Software
      url: software/
    - name: Musik
      url: musik/

socialIcons:
  - name: LinkedIn
    url: https://www.linkedin.com/company/artewil
  - name: Codeberg
    url: https://codeberg.org/vilchy
    hreflang: en
  - name: GitHub
    url: https://github.com/vilchy
    hreflang: en
  - name: Pixabay
    url: https://pixabay.com/de/users/rotepian-14403633/
  - name: Discogs
    url: https://www.discogs.com/artist/1884887-Artur-Wilniewczyc
  - name: YouTube
    url: https://youtube.com/playlist?list=PLeMSV_3ixFZlS4cU7VSM3TujMToW2AqYo
