# SPDX-FileCopyrightText: 2023-2024 Artur Wilniewczyc <code@artewil.com>
#
# SPDX-License-Identifier: MIT

baseURL: "/"
title: ArteWil
copyright: © 2024 Artur Wilniewczyc.
theme: PaperMod

enableRobotsTXT: true

disableKinds:
  - taxonomy
  - term

minify:
  disableXML: true
  minifyOutput: true

defaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 1
    menu:
      main:
        - name: Software
          url: software/
          weight: 5
        - name: Music
          url: music/
  pl:
    contentDir: content/pl
    languageName: Polski
    weight: 2
    menu:
      main:
        - name: Oprogramowanie
          url: oprogramowanie/
          weight: 5
        - name: Muzyka
          url: muzyka/
  de:
    contentDir: content/de
    languageName: Deutsch
    weight: 3
    menu:
      main:
        - name: Software
          url: software/
          weight: 5
        - name: Musik
          url: musik/

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false

params:
  env: production
  title: ArteWil
  keywords: [Portfolio]
  author: Artur Wilniewczyc
  images: ["/logo.png"]
  showBreadCrumbs: true

  schema:
    sameas: ["https://www.linkedin.com/company/artewil"]
    authorurl: https://musicbrainz.org/artist/522591b8-f53f-4fa2-a4ba-26416aa31a89

  assets:
    disableFingerprinting: false
